[package]
name = "hyperspectra"
version = "0.0.0"
authors = ["noah <nomaxx117@gmail.com>"]
edition = "2018"

# Runtime dependencies
[dependencies]
# CLI arg parsing
structopt = "0.3.18"

# Regex library
regex = "1.4"

# Fork of memmap2 library. I added support for MMAP_POPULATE, to enable page cache preloading.
[dependencies.memmap2]
git = "https://github.com/Noah-Kennedy/memmap2-rs"

# Provides status bar
[dependencies.indicatif]
version = "0.15.0"

# Provides numeric traits and generic numeric functions
[dependencies.num]
version = "0.3.0"

# Image processing library, used to generate PNG images.
[dependencies.image]
version = "0.23.11"
default-features = false
features = ["png"]

# Development dependencies
# Used primarily for tests
[dev-dependencies]
subprocess = "0.2.6"