[package]
name = "hyperspectra"
version = "0.0.0"
authors = ["noah <nomaxx117@gmail.com>"]
edition = "2018"

[dependencies]
memmap2 = "0.1.0"
rayon = "1.4"
structopt = "0.3.18"

[dependencies.indicatif]
version = "0.15.0"
features = ["improved_unicode", "with_rayon"]

[dependencies.num]
version = "0.3.0"
