[package]
name = "hyperspectra"
version = "0.3.0"
authors = ["noah <nomaxx117@gmail.com>"]
edition = "2018"

# Runtime dependencies
[dependencies]
# CLI arg parsing
structopt = "0.3.18"

# Regex library
regex = "1.4"

# Provides numeric traits and generic numeric functions
num = "0.3.0"

# Provides status bar
indicatif = "0.15.0"

memmap2 = "0.1.0"

# Image processing library, used to generate PNG images.
[dependencies.image]
version = "0.23.12"
default-features = false
features = ["png"]