[package]
name = "hyperspectra"
version = "0.3.0"
authors = ["noah <nomaxx117@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.18"
rayon = "1.5"
regex = "1.4"
num = "0.3.0"
memmap2 = "0.1.0"

[dependencies.nalgebra]
version = "0.23.1"

[dependencies.indicatif]
version = "0.15.0"
features = ["improved_unicode"]

[dependencies.image]
version = "0.23.12"
default-features = false
features = ["png"]