[workspace]
members = [
    "vanadium-core",
    "vanadium-benches",
    "vanadium-io",
    "vanadium-cli"
]

[profile.release]
#lto = "fat"
#codegen-units = 1
#debug-assertions = false
#overflow-checks = false