[package]
name = "hyperspectra"
version = "0.0.0"
authors = ["noah <nomaxx117@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.4"
structopt = "0.3.18"
regex = "1.4"

[dependencies.memmap2]
git = "https://github.com/Noah-Kennedy/memmap2-rs"

[dependencies.indicatif]
version = "0.15.0"
features = ["with_rayon"]

[dependencies.num]
version = "0.3.0"