[package]
name = "envi-header"
version = "0.1.0"
authors = ["noah <nomaxx117@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.regex]
version = "1.4"
default-features = false
features = ["std"]