[package]
name = "vanadium-core"
version = "0.1.0"
edition = "2018"

[features]
async = ["futures"]
header-parsing = ["serde"]
tokio-support = ["tokio", "async"]
tokio-uring-support = ["tokio-uring", "async"]
glommio-support = ["glommio"]

[dependencies]
num-traits = "^0.2.14"
nalgebra = "^0.28.0"
byteorder = "^1.4"

[dependencies.futures]
version = "^0.3.15"
optional = true

[dependencies.serde]
version = "^1.0.0"
features = ["derive"]
optional = true

[dependencies.tokio]
version = "^1.9.0"
features = ["sync"]
optional = true

[dependencies.tokio-uring]
version = "0.1.0"
optional = true

[dependencies.glommio]
version = "^0.5.0"
optional = true